### PR TITLE
Support boolean values

### PR DESCRIPTION
**Pull request by lawrence-mbf**
## Motivation

[h5py boolean values](https://docs.h5py.org/en/stable/faq.html?highlight=bool#what-datatypes-are-supported) were not supported correctly.

## How to test the behavior?

See https://github.com/NeurodataWithoutBorders/matnwb/issues/466#issue-1396855818

This PR only fixes a subset of issues when reading this file.

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by bendichter** [comment]
@lawrence-mbf this looks good to me! Do you know what lines of code are untested and how they might be tested? I can see that you added a test that does I/O for bool, but I'm not crazy about lowering our test coverage numbers if we can avoid it

**Comment by lawrence-mbf** [comment]
@bendichter I'll take a look at it. I think some of it is because of certain branches in `getRow` being added in.

**Comment by lawrence-mbf** [comment]
@bendichter coverage improved

**Comment by CodyCBakerPhD** [comment]
Heya, this is needed for https://github.com/catalystneuro/ndx-extract/pull/4 and other things around the ecosystem, I'm sure. Anything left to do here?

**Comment by CodyCBakerPhD** [comment]
When used with https://github.com/catalystneuro/ndx-extract/pull/4 creates values appearing like

image

in HDFView, and when using `h5py` they are read back as `np.bool_`, so looks good to me!

**Review by CodyCBakerPhD — APPROVED** [review]

**Pull request merged**
