### PR TITLE
create icephys.mlx and corresponding html that mimics python tutorial

### PR DESCRIPTION
**Pull request by bendichter**

### CODE REVIEW

**Comment by bendichter** [comment]
ah, I think I forgot to check that in.

**Comment by bendichter** [comment]
@ln-vidrio try now

**Comment by ln-vidrio** [comment]
That part's working now. I do get a new error on line 172-175 though
```MATLAB
[simultaneous_recordings_vector_data, simultaneous_recordings_vector_index] = util.create_indexed_column( ...
    {0,}, ...
    'Column with references to one or more rows in the SimultaneousRecordingsTable table', ...
    sequential_recordings);
```
Where `sequential_recordings` is either referenced before its creation or is actually referencing `ic_sim_recs_table`

**Comment by ln-vidrio** [comment]
Oh wait, that looks like it might be on my end.

**Comment by ln-vidrio** [comment]
No, I'm definitely getting an `Unrecognized function or variable 'sequential_recordings'` error.

**Review by ln-vidrio — APPROVED** [review]

**Review by ln-vidrio — COMMENTED** [review]
I do get a new error on line 172-175 though

```MATLAB
[simultaneous_recordings_vector_data, simultaneous_recordings_vector_index] = util.create_indexed_column( ...
    {0,}, ...
    'Column with references to one or more rows in the SimultaneousRecordingsTable table', ...
    sequential_recordings);
```
Where `sequential_recordings` is either referenced before its creation or is actually referencing `ic_sim_recs_table`

**Comment by bendichter** [comment]
@ln-vidrio thanks for catching that. Can you try again?

**Comment by bendichter** [comment]
@ln-vidrio is there a way of running tests on the xml files?

**Comment by ln-vidrio** [comment]
@bendichter  I'm not aware of any other than simply running them. I would've thought that publishing them ran the tests but sometimes it doesn't appear to be the case.

**Pull request merged**
