### PR TITLE
Datastub subsref

### LINKED ISSUE #120: use subsref for more intuitive DataStub load
The syntax for data stub load is still a little wonky. Vijay recommended we might think about using [subsref](https://www.mathworks.com/help/matlab/ref/subsref.html) to make the syntax mirror matlab's standard array selection syntax.

### PR DESCRIPTION
**Pull request by ln-vidrio**
Add subsref behavior to DataStub.
This is currently WIP as it may require subtle changes to all classes using DataStub.
Fixes #120, #221

### CODE REVIEW

**Comment by bendichter** [comment]
Thanks for working on this!

**Comment by bendichter** [comment]
How do you read the entire dataset? `stub(:,:,:)` should work, but it would also be nice to have a method where you don't need to know the number of dimensions. Does `stub.load` still work?

**Comment by ln-vidrio** [comment]
> How do you read the entire dataset?

`stub(:)` should work as long as the stub is not empty.

`load` was not touched and I've just added a special load_mat_style which just reuses load_h5_style with special conditions.

**Comment by bendichter** [comment]
`(:)` flattens the array though. What is the best approach to read the entire dataset without flattening it?

**Comment by ln-vidrio** [comment]
It actually only returns one element right now, it shouldn't flatten the array.

**Comment by bendichter** [comment]
In standard MATLAB, `(:)` flattens the array. Do you think we should have that subsref act differently here?

**Comment by ln-vidrio** [comment]
Wasn't aware of that, is that true for (:, :) as well for arrays with more than two dimensions?
To load the entire dataset without flattening, you could just require calling `load()`. I'm not sure if you can express that via subsref.

**Comment by bendichter** [comment]
> is that true for (:, :) as well for arrays with more than two dimensions?

I don't think so, I think it's unique to `(:)`

 > To load the entire dataset without flattening, you could just require calling load(). I'm not sure if you can express that via subsref.

That sounds good. I just wanted to make sure that capability remained.

**Comment by ln-vidrio** [comment]
So I tested it out and it actually does flatten based on how many indices there are versus how many dimensions are in the dataset, so I'll be adding that.

**Comment by bendichter** [comment]
Hm ok, I've never seen it used outside of the single dimension case. Sounds good!

**Comment by ln-vidrio** [comment]
@bendichter 
Caveats:
- DataStub is Sealed so no subclassing of DataStub
- DataStub.load() is still the recommended way to load the entire dataset at a normal shape.

**Pull request merged**
