### PR TITLE
Tighten Character Array checks in Attributes

### LINKED ISSUE #289: descriptions should not be allowed to be cell arrays
The "description" field should not be able to be an array. A user can enter

```matlab
timeseries = types.core.TimeSeries( ...
    'data', [1,2,3], ...
    'description', {'aa' 'aa'}, ...
    'starting_time_rate', 100, ...
    'data_unit', 'na');
```

and no error is raised, but this results in an object with an incorrect description that cannot be opened by PyNWB

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #289

### CODE REVIEW

**Comment by bendichter** [comment]
@ln-vidrio this works well!

**Comment by bendichter** [comment]
Would it be possible to also add a test so that we can keep our coverage up?

**Comment by ln-vidrio** [comment]
I'll take a look but none of the NwbFile.m coverage is connected to any of the actual changes in the commit.

**Comment by bendichter** [comment]
OK, well no need to hold up the commit if it's not straightforward to do

**Pull request merged**
