### PR TITLE
cache DataStub data

### LINKED ISSUE #412: Cache File and Dataset IDs for DataStubs
- [ ] cache file and dataset ids on load and destroy them if possible.
- [ ] use a different solution for bound pipes which may cause file corruption if the dataset is not properly closed.

### PR DESCRIPTION
**Pull request by lawrence-mbf**
Fixes #412 

## Motivation

Add caching to data stubs.

## How to test the behavior?
```
% dataStub being some dataStub.
dims = dataStub.dims; % should be much faster on an external or network drive due to caching behavior.
```

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Review by bendichter — APPROVED** [review]

**Review by bendichter — APPROVED** [review]

**Comment by bendichter** [comment]
@lawrence-mbf is this ready to merge?

**Comment by lawrence-mbf** [comment]
@bendichter I don't think so. There was still some instability in the last hackathon that caused full MATLAB crashes and the "solution" in the last commit only really resolved it at the high level. Unfortunately, I narrowed this down to a MATLAB bug present in versions older than R2021a where H5F.close() would close all file IDs, even if you've cloned it properly.

To reproduce:
```MATLAB
filename = 'test.nwb';
datasetPath = '/file_create_date';

fid = H5F.open(filename, 'H5F_ACC_RDONLY', 'H5P_DEFAULT');
sourceDid = H5D.open(fid, datasetPath);
sourceGid = H5G.open(fid, '/general');

% this can occur with both H5F.open and H5F.reopen
fidReopened = H5F.open(filename, 'H5F_ACC_RDONLY', 'H5P_DEFAULT');
% fidReopened = H5F.reopen(fid);
didReopened = H5D.open(fidReopened, datasetPath);

% The error only occurs when ALL HDF5 IDs are closed including the source file id.
% not closing any of the below ids keeps it "alive" and does not cause a crash.
H5D.close(sourceDid);
H5G.close(sourceGid);
H5F.close(fid);

data = H5D.read(didReopened); % MATLAB crashes here.
```

**Comment by bendichter** [comment]
I see. Is there any way we could file this with Mathworks?

**Comment by lawrence-mbf** [comment]
I suppose you could but it is technically fixed in R2021a and later. You could also bring it up in the working group I suppose.

**Comment by bendichter** [comment]
I think they still maintain patches for older versions

**Pull request closed without merging**
