### PR TITLE
Use RunMATLABTests task in Azure Pipelines

### LINKED ISSUE #255: Tests are failing but CI is passing
Hi,

I just noticed that some tests are failing, for example here:

https://dev.azure.com/NeurodataWithoutBorders/matnwb/_build/results?buildId=1340&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5c7b8cce-d95f-56ce-c8fa-472b8c0934b1&l=19

but the job is passing. IS this intended. Couple thoughts:

The run MATLAB command line doesn't need its own try-catch. For example this currently in the azure-pipelines file:

`"try, results = nwbtest; if isempty(results), exit(1); end; catch err, disp(err.message); exit(1); end"`

Can be replaced by this:

`"results = assertSuccess(nwbtest);  assert(~isempty(results), 'No tests ran'); "`

The build will fail if the command errors, but the command won't error if a test fails unless you add assertSuccess.

Also, you may consider using the RunMATLABTests task, which also generates Junit and coverage artifacts just like you are doing manually, but may be easier and less error prone. 

Hope that helps!
Andy

### PR DESCRIPTION
**Pull request by rly**
Fix #255.

### CODE REVIEW

**Comment by ln-vidrio** [comment]
Try adding the `selectByFolder` option in `runMATLABtests` as per https://marketplace.visualstudio.com/items?itemName=MathWorks.matlab-azure-devops-extension#run-matlab-tests

**Comment by rly** [comment]
@ln-vidrio Oops! Looks like we made two PRs at the same time (#256).

> Try adding the `selectByFolder` option in `runMATLABtests`
Will do.

**Comment by ln-vidrio** [comment]
@rly I closed mine, yours looks better haha.

**Comment by ln-vidrio** [comment]
I guess you do still need to at least call `generateCore` as a step before running tests just so code coverage can parse `NwbFile.m` correctly.

**Comment by rly** [comment]
Huh, does `nwbtest` call `generateCore`? It seemed to work (at least partially) before...

**Comment by ln-vidrio** [comment]
I think it's something that the task does that's different than `nwbtest`.

I've recently changed the tests to run `generateCore` in temp directories so you shouldn't need to run `generateCore` before running `nwbtest`. I'm not sure why it complains now.

**Comment by ln-vidrio** [comment]
As a side note, when I run the script contents in my local repo, there are no tests found for some reason. I wonder if packages are just ignored.

**Comment by rly** [comment]
I think the pipeline works now. 4 tests are failing due to int32 vs int64 mismatch on a roundtrip with PyNWB (as they were before).

**Pull request merged**
