### PR TITLE
Lower extra properties, datasets, groups, and links to warn instead of error

### LINKED ISSUE #245: Error when loading files with non-standard attributes
I am using your matnwb suite to attempt to open the files in DANDI Archive 20 (https://gui.dandiarchive.org/#/dandiset/000020). More info can be found about the data in that archive here: https://portal.brain-map.org/explore/classes/multimodal-characterization/multimodal-characterization-mouse-visual-cortex. I was informed by the makers of the file (Allen Institute) that they were created using PyNWB 1.3.2 using NWB schema 2.2.5.

When I download a file in this set and attempt to read it using nwbRead(), I get the error message that I've included at the end of this file message. If I download files from another DANDI set created at a later date (DANDI Archive 50), the file reads just fine. I think this may have to do with migrating schema, but I don't know how to get access to older versions of the schema, so that I might figure this out. Any help would be greatly appreciated.

>> nwbRead('sub-605770584_ses-606098055_icephys.nwb')

ERROR MESSAGE

Array indices must be positive integers or logical values.

Error in file.fillExport (line 24)
    prop = pathProps{end};

Error in file.fillClass (line 93)
exporterFcns = file.fillExport(nonInherited, class, depnm);

Error in file.writeNamespace (line 22)
        fwrite(fid, file.fillClass(className, Namespace, processed, ...

Error in nwbRead>tryWriteSpec (line 106)
    file.writeNamespace(namespaceName);

Error in nwbRead>generateSpec (line 94)
    if ~tryWriteSpec(name)

Error in nwbRead>checkEmbeddedSpec (line 44)
    generateSpec(fid, h5info(filename, specLocation));

Error in nwbRead (line 27)
    specLocation = checkEmbeddedSpec(filename);

### PR DESCRIPTION
**Pull request by lawrence-mbf**
## Motivation

Fixes #245 

## How to test the behavior?

Reading from the files mentioned in #245 should not fail with the specific extra properties error. It should now be a warning you can hide.

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by lawrence-mbf** [comment]
@rly Note that the example file still fails due to an invalid dataset in `/general/generated_by` dataset which is not a `LabMetaData` error.

**Comment by rly** [comment]
> @rly Note that the example file still fails due to an invalid dataset in `/general/generated_by` dataset which is not a `LabMetaData` error.

What is invalid about this dataset?

In addition to lowering extra attributes to warn instead of error, can we also lower extra datasets, links, and groups to warn instead of error? Is that already handled by the PR?

**Comment by lawrence-mbf** [comment]
> In addition to lowering extra attributes to warn instead of error, can we also lower extra datasets, links, and groups to warn instead of error? Is that already handled by the PR?

Will do, just need to make one more change.

**Comment by lawrence-mbf** [comment]
@rly file is readable now.

**Comment by rly** [comment]
Great. Thanks a bunch. My knowledge of matnwb internals is limited. @bendichter could you review this?

**Comment by bendichter** [comment]
@lawrence-mbf this looks good. Would you be able to add a test or two testing this new flexbility?

**Comment by lawrence-mbf** [comment]
@bendichter tests added with some added coverage

**Comment by bendichter** [comment]
@lawrence-mbf would it be possible to increase test coverage? We'll need to get coverage up by next year, so I'd prefer not to add code that takes us further from that goal

**Comment by lawrence-mbf** [comment]
> @lawrence-mbf would it be possible to increase test coverage? We'll need to get coverage up by next year, so I'd prefer not to add code that takes us further from that goal

I think I can add one more for test for https://github.com/NeurodataWithoutBorders/matnwb/blob/694158abfb184136151013e5d469e18dee55335a/%2Btypes/%2Buntyped/Set.m#L146-L151 but most of the other changes are just one-line diffs. If you mean generally I can open up a ticket for that.

**Review by bendichter — DISMISSED** [review]

**Pull request merged**
