### PR TITLE
Allow unit vectordata

### LINKED ISSUE #238: error reading Neuropixel file
When opening [this Neuropixel file](https://girder.dandiarchive.org/api/v1/item/5eda859399f25d97bd27985d/download), I get the following error:

```matlab
>> clear;
>> generateCore();
>> nwb = nwbRead('/Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb');
Error using types.util.checkUnset (line 13)
Unexpected properties {unit}.

Your schema version may be incompatible with the file.  Consider checking the schema
version of the file with `util.getSchemaVersion(filename)` and comparing with the YAML
namespace version present in nwb-schema/core/nwb.namespace.yaml

Error in types.hdmf_common.VectorData (line 26)
            types.util.checkUnset(obj, unique(varargin(1:2:end)));

Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 33)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
```

This file has a slightly older version of NWB

```python
>> util.getSchemaVersion('/Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb')

ans =

  1×1 cell array

    {'2.2.2'}
```

so I tried downloading nwb-schema and checking out the proper version, but that did not fix the issue and resulted in the same error.

Trying pynwb's validation, there were errors, but not ones that look relevant here:

```bash
$ python -m pynwb.validate /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb
Validating /Volumes/easystore5T/data/Allen/neuropixel/sub-699733573_ses-715093703.nwb against cached namespace information using namespace ndx-aibs-ecephys.
 - found the following errors:
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeA.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeB.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeC.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeD.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeE.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
EcephysElectrodeGroup/has_lfp_data (general/extracellular_ephys/probeF.has_lfp_data): incorrect type - expected 'bool', got 'bool_'
```

### PR DESCRIPTION
**Pull request by lawrence-mbf**
Fixes #238 

## Motivation

See #238 and friends

## How to test the behavior?

See #238 and friends. A good example file is DANDIset 000022

- `waveform_mean`, `waveform_sd`, and `waveforms` attributes:
  - `unit`
  - `sampling_rate`
- `spike_times` attributes:
  - `resolution`

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by rly** [comment]
Will you add the same workaround for the `sampling_rate` attribute on the "waveform_mean", "waveform_sd", and "waveforms" named VectorData, and the `resolution` attribute on the "spike_times" named VectorData?

https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L248
https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L193

**Comment by lawrence-mbf** [comment]
@rly or @bendichter 

> Will you add the same workaround for the `sampling_rate` attribute on the "waveform_mean", "waveform_sd", and "waveforms" named VectorData, and the `resolution` attribute on the "spike_times" named VectorData?
> 
> https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L248 https://github.com/NeurodataWithoutBorders/nwb-schema/blob/dev/core/nwb.misc.yaml#L193

I can do that but could either @rly or @bendichter draft a python script that creates a Unit table with these attributes so I can add it to the python tests?

**Comment by bendichter** [comment]
I did a simple spot check on [this dataset](https://api.dandiarchive.org/api/dandisets/000230/versions/0.220506.1516/assets/d8e0ccfb-fc0d-4fd2-8b26-be8f187cc2c0/). Read was broken before and with this change read is fixed. I'll try a few more spot checks.

**Comment by bendichter** [comment]
@yarikoptic would it be possible to run the healthstatus checks against this branch? It appears to work but I want to be thorough

**Comment by yarikoptic** [comment]
not "easily". We have https://github.com/dandi/dandisets-healthstatus/issues/20 but not yet pursued that direction.
and unfortunately currently running healthchecks, especially matlab one, is way too slow. heh.   But if you know which dandiset/files you would like to run them on, you could even use this KISS helper https://github.com/dandi/dandisets-healthstatus/blob/main/code/checknwb.sh - just tune to your branch etc.

**Comment by bendichter** [comment]
Ueli's lab has confirmed that this works for them, fixing a write command that uses waveform_mean.sampling_rate and waveform_mean.unit

**Review by bendichter — APPROVED** [review]

**Review by bendichter — APPROVED** [review]

**Pull request merged**
