### PR TITLE
Refactor addRawData to flip append dims

### LINKED ISSUE #364: addRow function appending to wrong dimension of multidimensional matrices
Given MATLAB's rows-last mode of input-output with NWB files, the .addRow method of `DynamicTable` objects should append to last dimension of multi-dimensional columns. 

An example:

```matlab
file= NwbFile( ...
    'session_start_time', '2021-01-01 00:00:00', ...
    'identifier', 'ident1', ...
    'session_description', 'test' ...
    );

colnames = {'start_time', 'stop_time', 'randomvalues'};
multi_dim_table1 = types.core.TimeIntervals(...
    'description', 'test dynamic table column',...
    'colnames', colnames);
            
for i = 1:100
    multi_dim_table1.addRow(...
        'start_time', i,...
        'stop_time', i+1,...
        'randomvalues',rand(1,3,2),...
        'id', i-1);
end
file.intervals.set('multi', multi_dim_table1);
nwbExport(file, 'test_multi_addRow.nwb');
```
The code above produces a 100x3x2 array for the 'randomvalues' column which is encoded into file as 3x2x100 (see below). 

Screen Shot 2021-12-14 at 11 52 31 AM

The correct behavior would append each 3x2 matrix to the last dimension to produce a 3x2x100 array that is encoded into file as a 100x3x2 array.

This modification would resolve the concerns brought up in the discussion of issue #360

### LINKED ISSUE #390: VectorIndex data not updated properly for multidimensional ragged array columns
```matlab
% Create file
file= NwbFile( ...
    'session_start_time', '2021-01-01 00:00:00', ...
    'identifier', 'ident1', ...
    'session_description', 'test_file' ...
    );

% Define Vector Data Objects with first row of table
start_time_exp = types.hdmf_common.VectorData( ...
    'description', 'start times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1, ...  
        'maxSize', Inf ...
    ) ...
);
stop_time_exp = types.hdmf_common.VectorData( ...
    'description', 'stop times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 10, ...  
        'maxSize', Inf ...
    ) ...
);
random_exp = types.hdmf_common.VectorData( ...
    'description', 'random data column', ...
    'data', types.untyped.DataPipe( ...
        'data', rand(3,2,5), ...  #random data
        'maxSize', [3, 2, Inf], ...
        'axis', 3 ...
    ) ...
);
random_exp_index = types.hdmf_common.VectorIndex( ...
    'description', 'index to random data column', ...
     'target',types.untyped.ObjectView(random_exp), ...
    'data', types.untyped.DataPipe( ...
        'data', [5], ...  
        'maxSize', [Inf, 1], ...
        'axis', 1 ...
    ) ...
);
ids_exp = types.hdmf_common.ElementIdentifiers( ...
    'data', types.untyped.DataPipe( ...
        'data', 0, ...  # data must be numerical
        'maxSize', Inf ...
    ) ...
);
% Create expandable table
colnames = {'start_time', 'stop_time', 'randomvalues'};
file.intervals_trials = types.core.TimeIntervals( ...
    'description', 'test expdandable dynamic table', ...
    'colnames', colnames, ...
    'start_time', start_time_exp, ...
    'stop_time', stop_time_exp, ...
    'randomvalues', random_exp, ...
    'randomvalues_index', random_exp_index, ...
    'id', ids_exp ...
);  
% Export file
nwbExport(file, 'multiRaggedExpandableTableTest.nwb');
% Read in file
read_file = nwbRead('multiRaggedExpandableTableTest.nwb');
% add individual rows
read_file.intervals_trials.addRow( ...
    'start_time', 2, ...
    'stop_time', 20, ...
    'randomvalues', rand(3,2,6), ...
    'id', 1 ...
);
```

Output after `addRow` 
```matlab

>> read_file.intervals_trials.vectordata.get('randomvalues').data.internal

ans = 

  BoundPipe with properties:

            config: [1×1 types.untyped.datapipe.Configuration]
    pipeProperties: {1×2 cell}
              stub: [1×1 types.untyped.DataStub]
              axis: 3
            offset: 11
          dataType: 'double'
           maxSize: [3 2 Inf]
              dims: [3 2 11]
          filename: 'multiRaggedExpandableTableTest.nwb'
              path: '/intervals/trials/randomvalues'

read_file.intervals_trials.vectordata.get('randomvalues_index').data(:)

ans =

     5
     8
``` 

Second entry of `randomvalues_index` data should be 11. 

No issues for 1D ragged array columns.

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #390, Fixes #364

### CODE REVIEW

**Comment by ln-vidrio** [comment]
> 1. adding row to multidimensional column of table in memory

Unless I read you wrong, I believe we agreed that we wanted to limit the dimensions for in-memory concatenation to 2D matrices. Did you mean 3D matrices or should I just make the error message more clear?

**Comment by cechava** [comment]
> > 1. adding row to multidimensional column of table in memory
> 
> Unless I read you wrong, I believe we agreed that we wanted to limit the dimensions for in-memory concatenation to 2D matrices. Did you mean 3D matrices or should I just make the error message more clear?

Thanks for adding that helpful error message. The error on that point was on my part. I forgot that we had agreed on to use `DataPipes` for multidimensional column. Thanks for clarifying.

However, there's still some issues with the behavior of `DataPipe` when appending to a multidimensional array column. Example code:

```matlab
% Create file
file= NwbFile( ...
    'session_start_time', '2021-01-01 00:00:00', ...
    'identifier', 'ident1', ...
    'session_description', 'test_file' ...
    );

% Define Vector Data Objects with first row of table
start_time_exp = types.hdmf_common.VectorData( ...
    'description', 'start times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1, ...  
        'maxSize', Inf ...
    ) ...
);
stop_time_exp = types.hdmf_common.VectorData( ...
    'description', 'stop times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 10, ...  
        'maxSize', Inf ...
    ) ...
);
random_exp = types.hdmf_common.VectorData( ...
    'description', 'random data column', ...
    'data', types.untyped.DataPipe( ...
        'data', rand(3,2,5), ...  #random data
        'maxSize', [3, 2, Inf], ...
        'axis', 3 ...
    ) ...
);
random_exp_index = types.hdmf_common.VectorIndex( ...
    'description', 'index to random data column', ...
     'target',types.untyped.ObjectView(random_exp), ...
    'data', types.untyped.DataPipe( ...
        'data', [5], ...  
        'maxSize', [Inf, 1], ...
        'axis', 1 ...
    ) ...
);
ids_exp = types.hdmf_common.ElementIdentifiers( ...
    'data', types.untyped.DataPipe( ...
        'data', 0, ...  # data must be numerical
        'maxSize', Inf ...
    ) ...
);
% Create expandable table
colnames = {'start_time', 'stop_time', 'randomvalues'};
file.intervals_trials = types.core.TimeIntervals( ...
    'description', 'test expdandable dynamic table', ...
    'colnames', colnames, ...
    'start_time', start_time_exp, ...
    'stop_time', stop_time_exp, ...
    'randomvalues', random_exp, ...
    'randomvalues_index', random_exp_index, ...
    'id', ids_exp ...
);  
% Export file
nwbExport(file, 'multiRaggedExpandableTableTest.nwb');
% Read in file
read_file = nwbRead('multiRaggedExpandableTableTest.nwb');
% add individual rows
read_file.intervals_trials.addRow( ...
    'start_time', 2, ...
    'stop_time', 20, ...
    'randomvalues', rand(3,2,6), ...
    
```

output after `addRow` line
```matlab
>>  read_file.intervals_trials.vectordata.get('randomvalues').data.internal

ans = 

  BoundPipe with properties:

            config: [1×1 types.untyped.datapipe.Configuration]
    pipeProperties: {1×2 cell}
              stub: [1×1 types.untyped.DataStub]
              axis: 3
            offset: 11
          dataType: 'double'
           maxSize: [3 2 Inf]
              dims: [3 2 11]
          filename: 'multiRaggedExpandableTableTest.nwb'
              path: '/intervals/trials/randomvalues'

>> read_file.intervals_trials.vectordata.get('randomvalues_index').data(:)

ans =

     5
     6
```
Second entry of `randomvalues_index` data should be 11.

**Review by cechava — CHANGES_REQUESTED** [review]
see comment above for requested changes.

**Comment by ln-vidrio** [comment]
@cechava you have to include the `axis` keyword argument and set the dimension manually in datapipes. However, this is an interesting usage case. Do you and @bendichter think this would be a good idea to read the last `Inf` in the `maxSize` keyword argument as the axis dimension if no `axis` was provided?

**Comment by ln-vidrio** [comment]
Given the keyword arguments:
| Axis | maxSize | data | Result |
| - | - | - | - |
| x | x | x | Use maxSize as bound and axis as dimension for appending. Check if data is within size bounds |
| x | x | _ | Use maxSize as bound and axis ad dimension for appending. |
| x | _ | x | Generate a maxSize by using the bounds provided by data and set the dimension at the axis dimension to Inf |
| x | _ | _ | Not sure about this. Perhaps assume ones for all dimensions less than the axis dimension? If axis == 3 then the maxSize is [1, 1, Inf] |
| _ | x | x | Check if data is within maxSize bounds. Check for Inf in maxSize and use the last occurring one. If maxSize has no Inf bounds then assume the last dimension in maxSize |
| _ | x | _ | Same as above but without the data check. |
| _ | _ | x | Not sure about this one either. Perhaps assume the last dimension in data? |
| _ | _ | _ | Most likely an error. |

**Comment by cechava** [comment]
> @cechava you have to include the `axis` keyword argument and set the dimension manually in datapipes. However, this is an interesting usage case. Do you and @bendichter think this would be a good idea to read the last `Inf` in the `maxSize` keyword argument as the axis dimension if no `axis` was provided?

I did set the 'axis' argument  for the `randomvalues` and `randomvalues_index` columns. These are the relevant columns for this test, which is to verify the behavior of `addRow` for multidimensional columns.
I did not set `axis` for `start_times`, `stop_times, or `ids` columns intentionally so that they would be saved as data sets of size (N,).  These are not relevant for this test.

**Comment by ln-vidrio** [comment]
@cechava Oh I just missed that then.

**Review by cechava — APPROVED** [review]
works great. Thanks @ln-vidrio

**Pull request merged**
