### PR TITLE
281 legacy 202 support

### LINKED ISSUE #281: opening dandiset 19
When trying to open https://dandiarchive.org/dandiset/000019/draft

I get the following error:

```matlab
>> nwbRead('/Users/bendichter/Downloads/sub-EC2_ses-EC2-B9.nwb');
Unable to resolve the name types.core.DynamicTableRegion.

Error in io.parseDataset (line 72)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 22)
    dataset = io.parseDataset(filename, datasetInfo, fullPath,
    Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 35)
nwb = io.parseGroup(filename, h5info(filename), Blacklist);
 ```
Looking at the dataset in HDFView, the file appears to be NWB version 2.0.2:
image

but I only see schema versions back to 2.2.0:
image

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #281

### CODE REVIEW

**Comment by bendichter** [comment]
This works for me with

```matlab
>> generateCore('2.0.2');
>> nwb = nwbRead('/Users/bendichter/Downloads/sub-EC2_ses-EC2-B9.nwb');
```

**Comment by bendichter** [comment]
This works, but we get a pretty unhelpful error is users don't run `generateCore('2.0.2');` first. Would it be possible to check the version of the schema in the NWB file and offer more helpful guidance? Something like:

> This NWB file is using NWB schema version X, but MatNWB has been configured for NWB schema version Y. Consider using `generateCore(X)` to reconfigure MatNWB for this data.

**Comment by ln-vidrio** [comment]
I thought I automated that in fact. That's odd.

**Comment by ln-vidrio** [comment]
If the version string shows up in the `nwb-schema` directory, `nwbRead` should now call `generateCore` with that version string automatically.

**Comment by ln-vidrio** [comment]
Probably don't want to generate every read actually.

**Pull request merged**
