### PR TITLE
Bugs/write cached spec

### LINKED ISSUE #149: Cached Spec Writes are Unsupported
At the current moment, MatNWB does not support writing schema files or cached specs.

The reason for not writing cached specs stems from the fact that cached specs are, by default, only written in JSON format.  This is not possible with MatNWB's YAML parser.

However, should we work around this issue, the default YAML string produced by the YAML parser on export() produces a YAML with specific tags that end up breaking the default pynwb yaml importer, shown below:
```
!java.util.LinkedHashMap
namespaces: 
- !java.util.LinkedHashMap
   name: core
   doc: NWB namespace
...
   full_name: NWB core
   schema: 
   - !java.util.LinkedHashMap
      source: nwb.base.yaml
      title: Base data types
      doc: This source module contains base data types used throughout the NWB:N data format.
   - !java.util.LinkedHashMap
      source: nwb.epoch.yaml
      title: Epochs
      doc: This source module contains neurodata_types for epoch data.
...
   version: 2.0.1
```

### LINKED ISSUE #150: Cached Spec is Immutable to Schema Changes After Read
The cached spec in NWB is assumed to be fully transparent to the user.  The regular usage loop should be no different from nwbRead() nwbExport() usage.

At the current moment, matnwb simply drops the embedded spec data after generating the classes (due to write issues see #149).  A simple fix for preexisting embedded spec data is to store the globs privately in `nwbfile` and rewrite it back out on `nwbExport()`.

However, if a user were to add a new extension object whose schema did not exist in the cached spec beforehand, then transferring the file no longer guarantees that the class is readable.  This is not checked for in matnwb and there are no mechanisms in place to add to the spec (again, due to #149) on such an event.

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #149  and Fixes #150 
Requires regenerating classes.

### CODE REVIEW

**Comment by bendichter** [comment]
@ln-vidrio sorry I left this hanging. If you could resolve the conflict I'll review right away

**Comment by ln-vidrio** [comment]
Resolved

**Comment by ln-vidrio** [comment]
That should be fixed now.  I'm now running into an error involving util.loadTrialAlignedTimerSeriesData.  Is that fixable on your end or is there something weird going on with untyped Set?

**Comment by bendichter** [comment]
I'm not running into this error:

```matlab
Subscripted assignment between dissimilar structures.

Error in schemes.loadCache (line 23)
    Cache(iMat) = load(matPath);

Error in schemes.exportJson (line 14)
Caches = schemes.loadCache(namespaceNames{:});

Error in NwbFile/embedSpecifications (line 86)
            JsonData = schemes.exportJson();

Error in NwbFile/export (line 40)
                obj.embedSpecifications(fid);

Error in nwbExport (line 35)
    export(nwb(i), filename);

Error in ecephys (line 278)
nwbExport(nwb, 'ecephys_tutorial.nwb')
```

**Comment by ln-vidrio** [comment]
That's a strange error and I'm unable to recreate it.  Could you delete the namespaces directory in your matnwb install directory and call generateCore again before running ecephys?

**Comment by bendichter** [comment]
@ln-vidrio that worked! Now I can see the error you are talking about. Let me take a look.

**Comment by bendichter** [comment]
@ln-vidrio do you get this error if you run `ecephys` twice?
```matlab
Error using schemes.Namespace/getParent (line 58)
Parent NWBContainer for class ImagingRetinotopy doesn't exist!
Missing Dependency?

Error in schemes.Namespace/getRootBranch (line 103)
            parent = obj.getParent(cursor('neurodata_type_def'));

Error in file.processClass (line 2)
branch = [{namespace.getClass(name)}
namespace.getRootBranch(name)];

Error in file.writeNamespace (line 14)
    [processed, classprops, inherited] =
    file.processClass(className, Namespace, pregenerated);

Error in spec.generate (line 35)
file.writeNamespace(NamespaceInfo.name);

Error in nwbRead>generateSpec (line 83)
    spec.generate(namespaceText, schemaMap);

Error in nwbRead>checkEmbeddedSpec (line 44)
    generateSpec(fid, h5info(filename, specLocation));

Error in nwbRead (line 27)
    specLocation = checkEmbeddedSpec(filename);

Error in ecephys (line 283)
nwb2 = nwbRead('ecephys_tutorial.nwb');
```

**Comment by ln-vidrio** [comment]
I'm getting it now after running it once, it looks like.  I'll look into it.

**Comment by bendichter** [comment]
@ln-vidrio yeah, running twice after a `generateCore`.

**Comment by ln-vidrio** [comment]
This should be fixed now, though the util.loadTrialAlignedTimerSeriesData issue remains.

**Comment by bendichter** [comment]
@ln-vidrio 

That error is fixed and now it's back to you with another error. 

```matlab
>> ecephys
```

```matlab
Not enough input arguments.

Error in io.parseGroup (line 9)
    io.parseAttributes(filename, info.Attributes,
    info.Name, Blacklist);

Error in types.untyped.ExternalLink/deref (line 43)
                    data =
                    io.parseGroup(obj.filename,
                    info);

Error in types.util.checkDtype (line 80)
        val = val.deref();

Error in
types.core.NWBFile/validate_general_subject (line
438)
        val =
        types.util.checkDtype('general_subject',
        'types.core.Subject', val);

Error in types.core.NWBFile/set.general_subject
(line 291)
        obj.general_subject =
        obj.validate_general_subject(val);

Error in ecephys (line 347)
nwb3.general_subject =
types.untyped.ExternalLink('ecephys_tutorial.nwb',... 
```

**Pull request merged**
