### PR TITLE
Fix Default Subclass Properties in checkUnset

### LINKED ISSUE #470: [Bug]: Unexpected attributes with nwbRead Dandiset 000115
### What happened?

`Unexpected properties {camera_device 1}` when using `nwbRead` to read data file `https://dandiarchive.org/dandiset/000115/0.210914.1732/sub-despereaux/sub-despereaux_ses-despereaux-07_behavior+ecephys.nwb`.

### Steps to Reproduce

```matlab
addpath(genpath(pwd));
generateCore();
nwb = nwbRead('pathname_to_file')

And `util.getSchemaVersion('pathname_to_file')` returns '2.3.0'
```

### Error Message

```matlab
Error using assert
Unexpected properties {camera_device 1}.

Your schema version may be incompatible with the file.  Consider checking the schema version of the
file with `util.getSchemaVersion(filename)` and comparing with the YAML namespace version present in
nwb-schema/core/nwb.namespace.yaml

Error in types.util.checkUnset (line 13)
assert(isempty(dropped),...

Error in types.ndx_franklab_novela.NwbImageSeries (line 11)
            types.util.checkUnset(obj, unique(varargin(1:2:end)));

Error in io.parseGroup (line 85)
    parsed = eval([Type.typename '(kwargs{:})']);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in io.parseGroup (line 38)
    subg = io.parseGroup(filename, group, Blacklist);

Error in nwbRead (line 59)
nwb = io.parseGroup(filename, h5info(filename), Blacklist); 
```
```


### Operating System

macOS

### Matlab Version

R2022b

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

### PR DESCRIPTION
**Pull request by lawrence-mbf**
Fixes #470 

## Motivation

See #470

## How to test the behavior?

See #470

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

**Comment by bendichter** [comment]
@lawrence-mbf do you know why these tests are failing? Would it be possible to fix them?

**Comment by lawrence-mbf** [comment]
@bendichter We're polluting our MatNWB install directory with schemas of other versions. All tests and tutorials should make sure when their code blocks call `generateCore` they add `'savedir', '.'` (`generateCore('savedir', '.')`) as arguments (saves the generated class files in the current directory which is usually a temporary file) or `nwbRead` with `'ignorecache'` (equivalent to `load_namespace=False` in pynwb).

As mentioned above, merging in #461 will fix it for the previously added tutorials.

**Comment by yarikoptic** [comment]
What is the plan for this PR - to be merged/released?

**Comment by lawrence-mbf** [comment]
@yarikoptic It can be merged. As mentioned, the test failures are already fixed upstream. Would you say that you approve of these changes?

**Review by bendichter — APPROVED** [review]

**Pull request merged**
