### PR TITLE
Add support for 1D `maxSize` option for datapipes

### LINKED ISSUE #375: Add 1-D dataset option to Datapipe
set `maxSize` to a single-dimension value

- [ ] Remove assertion check in blueprint pipe
- [ ] Test dataset read and write.

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #375

### CODE REVIEW

**Review by cechava — CHANGES_REQUESTED** [review]
Exported files look good. However, we are currently unable to add data to an exported file. See code snippet below.

```matlab
start_col = types.hdmf_common.VectorData( ...
    'description', 'start times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1:10, ... % HDF5 size (10,)
        'maxSize', Inf ...
    ) ...
);
stop_col = types.hdmf_common.VectorData( ...
    'description', 'stop times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1:10, ...  % HDF5 size (10,)
        'maxSize', Inf ...
    ) ...
);

ids_col = types.hdmf_common.ElementIdentifiers( ...
    'data', types.untyped.DataPipe( ...
        'data', (0:9), ...  % HDF5 size (10,)
        'maxSize', Inf ...
    ) ...
);
% Create table
trials_table = types.core.TimeIntervals(...
                 'description', 'test dynamic table column',...
                'colnames', {'start_time', 'stop_time'}, ...
                'start_time', start_col, ...
                'stop_time', stop_col, ...
                'id', ids_col ...     
);
% Create NwbFile object with required arguments
file = NwbFile( ...
    'session_start_time', '2022-01-01 00:00:00', ...
    'identifier', 'ident1', ...
    'session_description', 'test file' ...
);
% Assign to intervals_trials
file.intervals_trials = trials_table;
% Export
nwbExport(file, 'testFileWithDataPipes.nwb');
% Read in file
read_file = nwbRead('testFileWithDataPipes.nwb');
% add row
read_file.intervals_trials.addRow( ...
    'start_time',11, ...
    'stop_time',12, ...
    'id', 10 ...
);

Error using hdf5lib2
The rank of the dataspace does not correspond to the length of the START
argument.

Error in H5S.select_hyperslab (line 43)
H5ML.hdf5lib2('H5Sselect_hyperslab',space_id,op,h5_start,h5_stride,h5_count,h5_block);

Error in types.untyped.datapipe.BoundPipe/makeSelection (line 128)
            H5S.select_hyperslab(sid,...

Error in types.untyped.datapipe.BoundPipe/append (line 185)
            sid = obj.makeSelection(data_size);

Error in types.untyped.DataPipe/append (line 234)
            obj.internal.append(data);

Error in types.untyped.DataPipe/subsref (line 257)
                B = builtin('subsref', obj, S);

Error in types.util.dynamictable.addRawData>nestedAdd (line 111)
        Vector.data.append(data);

Error in types.util.dynamictable.addRawData (line 53)
nestedAdd(DynamicTable, indexChain, data);

Error in types.util.dynamictable.addVarargRow (line 41)
    types.util.dynamictable.addRawData(DynamicTable, rn, rv);

Error in types.util.dynamictable.addRow (line 56)
    types.util.dynamictable.addVarargRow(DynamicTable, varargin{:});

Error in types.hdmf_common.DynamicTable/addRow (line 118)
        types.util.dynamictable.addRow(obj, varargin{:});

Error in test_PR375 (line 44)
read_file.intervals_trials.addRow( ...
```

**Review by cechava — COMMENTED** [review]
last commit fixed things for 1D columns, but broke things down for the case when we want to save column vectors in HDF5.
snippet to reproduce:
```matlab
start_col = types.hdmf_common.VectorData( ...
    'description', 'start times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1:10, ... % HDF5 size (10, 1)
        'maxSize', [1, Inf], ...
        'axis', 2 ...
    ) ...
);
stop_col = types.hdmf_common.VectorData( ...
    'description', 'stop times column', ...
    'data', types.untyped.DataPipe( ...
        'data', 1:10, ...  % HDF5 size (10, 1)
        'maxSize', [1, Inf], ...
        'axis', 2 ...
    ) ...
);

ids_col = types.hdmf_common.ElementIdentifiers( ...
    'data', types.untyped.DataPipe( ...
        'data', (0:9), ...  % HDF5 size (10, 1)
        'maxSize', [1, Inf], ...
        'axis', 2 ...
    ) ...
);
% Create table
trials_table = types.core.TimeIntervals(...
                 'description', 'test dynamic table column',...
                'colnames', {'start_time', 'stop_time'}, ...
                'start_time', start_col, ...
                'stop_time', stop_col, ...
                'id', ids_col ...     
);
% Create NwbFile object with required arguments
file = NwbFile( ...
    'session_start_time', '2022-01-01 00:00:00', ...
    'identifier', 'ident1', ...
    'session_description', 'test file' ...
);
% Assign to intervals_trials
file.intervals_trials = trials_table;
% Export
nwbExport(file, 'testFileWithDataPipes.nwb');
% Read in file
read_file = nwbRead('testFileWithDataPipes.nwb');
% add row
read_file.intervals_trials.addRow( ...
    'start_time',11, ...
    'stop_time',12, ...
    'id', 10 ...
);

Error using types.untyped.datapipe.BoundPipe/expandDataset (line 144)
Data size cannot exceed maximum allocated size.

Error in types.untyped.datapipe.BoundPipe/append (line 180)
            obj.expandDataset(data_size);

Error in types.untyped.DataPipe/append (line 234)
            obj.internal.append(data);

Error in types.untyped.DataPipe/subsref (line 257)
                B = builtin('subsref', obj, S);

Error in types.util.dynamictable.addRawData>nestedAdd (line 111)
        Vector.data.append(data);

Error in types.util.dynamictable.addRawData (line 53)
nestedAdd(DynamicTable, indexChain, data);

Error in types.util.dynamictable.addVarargRow (line 41)
    types.util.dynamictable.addRawData(DynamicTable, rn, rv);

Error in types.util.dynamictable.addRow (line 56)
    types.util.dynamictable.addVarargRow(DynamicTable, varargin{:});

Error in types.hdmf_common.DynamicTable/addRow (line 118)
        types.util.dynamictable.addRow(obj, varargin{:});

Error in test_PR375 (line 97)
read_file.intervals_trials.addRow( ...
```

**Comment by ln-vidrio** [comment]
@cechava was that actually working in master?

**Comment by ln-vidrio** [comment]
Okay that was just a dumb question. The issue is that we do not derive the offset axis when reading in the nwb file. I'm surprised we haven't run into this sooner or I'm missing other parts of the code that **do** detect the axis elsewhere.

**Review by cechava — APPROVED** [review]
looks good and works great. Thanks!

**Comment by cechava** [comment]
@bendichter if this looks good to you, we can merge and update other PRs that use this functionality

**Comment by cechava** [comment]
@ln-vidrio I just noticed that the tests were failing after the latest commit in this PR. I think we should revert this merge or fix the issue in another PR. The failing tests seem to be related to legacy cases.
Screen Shot 2022-01-13 at 4 24 07 PM

**Comment by cechava** [comment]
I can't really understand how the changes that you made would lead to this error, but it seems to be the earliest time this arose.

**Comment by ln-vidrio** [comment]
Nah I've run into this in testing. If you re-run it sometimes passes and I definitely can't get it to fail that way on my machine. My best guess is that the environment is weird or it's just how linux handles temp directories.

**Comment by ln-vidrio** [comment]
Oh wait the issue right now has to do with the `checkConfig` implementation. It should be detecting that `ElementIdentifiers` should be in `core` not `hdmf_common`

**Comment by ln-vidrio** [comment]
Yeah it has to do with how temp environments are handled. It doesn't appear to be refreshing right on the CI instance and we are checking if `hdmf_common` exists.

**Pull request merged**
