### PR TITLE
Simplify DataPipe Construction

### LINKED ISSUE #195: default args for DataPipe
@IvanSmal and I have been able to successfully use `DataPipe` to compress data in NWB files, but we have found that the results can be very sensitive to the settings in `DataPipe`. There is little guidance for what would be reasonable parameters, and I would not expect many users to have a good intuition for what to use. I think it would be easier to use if we intelligently set some of these arguments. When MATLAB saves data using a an HDF5 backend using `save`, it has a way of automatically determining `compressionLevel` and `chunkSize`. It looks to me like MATLAB always defaults to GZIP level 3. It looks like the chunkSize is computed based on the shape of the matrix. I can't find where this is computed though.

Here is how I would propose we treat each argument of `DataPipe`:
* `maxSize`: Why is this an ordered arg and not a name, value arg? If `data` is supplied, and `maxSize` is not, `maxSize` should take the shape of data, except the `axis` dimension should be `Inf`, which would allow you to append in that dimension indefinitely.
* `dataType`: If `data` is supplied, we should infer `dataType` from it.
* `compressionLevel`: Use MATLAB default (3 I think)
* `chunkSize`: Use MATLAB default (if we can find the code for it)

### PR DESCRIPTION
**Pull request by ln-vidrio**
Fixes #195

### CODE REVIEW

**Comment by bendichter** [comment]
@ln-vidrio could you expose the shuffle option as well?

**Comment by ln-vidrio** [comment]
I'll look into it.

**Comment by ln-vidrio** [comment]
Major refactor needed.   Consider this pull request a wip draft.

**Comment by ln-vidrio** [comment]
@bendichter Shuffle has been added as a hasShuffle option.  Keep in mind that compression and chunking must be on.

**Comment by bendichter** [comment]
How would I append to this? When I write and then import back in, I get a dataStub with no `append` method:

```matlab

session_start_time = datetime(2018, 3, 1, 12, 0, 0, 'TimeZone', 'local');

nwb = NwbFile( ...
    'session_description', 'a test NWB File', ...
    'identifier', 'mouse004_day4', ...
    'session_start_time', session_start_time);

% generate data for demonstration
data = reshape(1:10000, 10, 1000);

data_pipe = types.untyped.DataPipe(...
    'axis', 1, ...
    'dataType','float64', ...
    'data', data, ...
    'maxSize', [Inf, 1000]);

time_series = types.core.TimeSeries( ...
    'starting_time', 0.0, ... % seconds
    'starting_time_rate', 200., ... % Hz
    'data', data_pipe, ...
    'data_unit', 'V');

nwb.acquisition.set('data_pipe_recording', time_series);

nwbExport(nwb, 'data_pipe_test.nwb')


nwb2 = nwbRead('data_pipe_test.nwb');

nwb2.acquisition.get('data_pipe_recording').data
```

**Comment by bendichter** [comment]
@ln-vidrio sorry, closed by accident

**Comment by ln-vidrio** [comment]
Evidently the pipeNwb. script does not make for great testing.  When you find the time, please pull and try again.

**Comment by bendichter** [comment]
The demo works as expected! @IvanSmal this should be an MVP for what you need.

@ln-vidrio this is an edge case, but the following did not behave as I expected:

```matlab

session_start_time = datetime(2018, 3, 1, 12, 0, 0, 'TimeZone', 'local');

nwb = NwbFile( ...
    'session_description', 'a test NWB File', ...
    'identifier', 'mouse004_day4', ...
    'session_start_time', session_start_time);

data_pipe = types.untyped.DataPipe(...
    'dataType', 'double', ...
    'maxSize', [Inf, 1000]);

time_series = types.core.TimeSeries( ...
    'starting_time', 0.0, ... % seconds
    'starting_time_rate', 200., ... % Hz
    'data', data_pipe, ...
    'data_unit', 'V');

nwb.acquisition.set('data_pipe_recording', time_series);

nwbExport(nwb, 'data_pipe_test.nwb')


nwb2 = nwbRead('data_pipe_test.nwb');

nwb2.acquisition.get('data_pipe_recording').data
```

returned an empty list. Would it be possible to for this to return an empty `DataPipe` with the appropriate settings?

**Comment by ln-vidrio** [comment]
There's one more edgecase as well.  Since we allowed file amending, there may be an error if you export to the same file twice.  Will look into that too.

**Comment by ln-vidrio** [comment]
@bendichter empty edge case should be fixed now.

**Comment by bendichter** [comment]
I found another edge case:

```matlab

fData=randi(250,1000,1000); % Create fake data

% create an nwb structure with required fields
nwb=NwbFile(...
    'session_start_time','2020-01-01 00:00:00',...
    'identifier','ident1',...
    'session_description','DataPipeTutorial');

fData_compressed=types.untyped.DataPipe('data', fData);

fdataNWB=types.core.TimeSeries(...
    'data', fData_compressed,...
    'data_unit', 'mV');

nwb.acquisition.set('data', fdataNWB);

nwbExport(nwb, 'DefaultChunks.nwb');
```

error:
```matlab
Error using types.untyped.datapipe.BlueprintPipe/write (line
162)
Data size must be bound by maxSize.
Data size was [1000, 1000].  maxSize configured to be [Inf,
1]

Error in types.untyped.DataPipe/export (line 177)
            obj.internal = obj.internal.write(fid,
            fullpath);

Error in types.core.TimeSeries/export (line 200)
                refs = obj.data.export(fid, [fullpath
                '/data'], refs);

Error in types.untyped.Set/export (line 177)
                    refs = v.export(fid, propfp, refs);

Error in types.core.NWBFile/export (line 508)
            refs = obj.acquisition.export(fid, [fullpath
            '/acquisition'], refs);

Error in NwbFile/export (line 58)
                refs = export@types.core.NWBFile(obj,
                output_file_id, '/', {});

Error in nwbExport (line 35)
    export(nwb(i), filename);
```

**Comment by ln-vidrio** [comment]
@bendichter that should be resolved now.

**Comment by bendichter** [comment]
@ln-vidrio is this ready to go?

**Comment by ln-vidrio** [comment]
@bendichter Sure. @IvanSmal Is #209 also ready?

**Pull request merged**
